spring:
  # 数据库配置
  # Redis 配置
  redis:
    database: 1
    host: redis
    port: 6379
    timeout: 5000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.207.158.188:3306/oj
    username: oj
    password: Coldplay789